### ISSUE TITLE
Add a LICENSE or LICENSE.md 

### ISSUE THREAD

**Issue by bmulkinfor** [SingingBush/barcode4j#10]
Please specify the license under which this fork of barcode4j is released.

**Comment by SingingBush** [comment]
As far as I'm aware it'll need to remain Apache License v2.0, this is also in the pom.xml:

```xml
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
```

I'll add a license file to the repo as well though.

**Comment by SingingBush** [comment]
done https://github.com/SingingBush/barcode4j/commit/3f0c15e17850ba6ada1197f3706f46d0e878e375
