### ISSUE TITLE
barcode4j parent 2.3.0 updated xmlgraphics to 2.10 but left batik at 1.17

### ISSUE THREAD

**Issue by JoshDM** [SingingBush/barcode4j#120]
xmlgraphics at 2.10 uses batik at 1.18  

Need to update org.apache.xmlgraphics.batik.version to 1.18

**Comment by JoshDM** [comment]
The reason I noticed this problem is that we had an odd issue with our code after moving to FOP 2.10

org/apache/fop/svg/SimpleSVGUserAgent.setSourceResolution(F)V (loaded from file:{..}/WEB-INF/lib/fop-core-2.10.jar called from class org.apache.fop.svg.SimpleSVGUserAgent 

fop-core 2.10 class SimpleSVGUserAgent extends batik-bridge class UserAgentAdapter.

batik 1.18 UserAgentAdapter added new methods to support source resolution that fop-core 2.10 is looking for. setSourceResolution(float) and the other methods do not exist in batik 1.17

Pushing batik 1.17 with xmlgraphics 2.10 is a breaking change.  1.18 is required.

**Comment by SingingBush** [comment]
doing a release now with all deps and plugins updated: https://github.com/SingingBush/barcode4j/commit/32fa8d9db774219619be465dd859d8a0de868748

see: https://github.com/SingingBush/barcode4j/releases

it usually takes an hour or so to get through maven central
