### ISSUE TITLE
Are there any plans to release this fork ? 

### ISSUE THREAD

**Issue by rzaq-alshoshan** [SingingBush/barcode4j#14]
Hi @SingingBush,
Do you have any plans on releasing this fork to maven ?
And what is the status of the project in general ? are you still invested in ? 
Thanks

**Comment by SingingBush** [comment]
yes indeed, in fact thanks for reminding me. I've been busy with other projects recently but will make some updates now.

**Comment by SingingBush** [comment]
I've updated the readme to be more clear about my intentions for version 2.* and 3.* releases.

I've just published version 2.2.0 to maven central. This should be a drop-in replacement for existing users. It should be available soon: https://central.sonatype.com/artifact/com.singingbush/barcode4j/

If you have need of one of the other modules or experience any problems please let me know.
