### ISSUE TITLE
remove dependency on Avalon Framework (used for Configuration)

### ISSUE THREAD

**Issue by SingingBush** [SingingBush/barcode4j#15]
the Avalon Framework is now retired so any dependency on it should be removed

https://cwiki.apache.org/confluence/display/excalibur/AvalonFramework

**Comment by SingingBush** [comment]
I have a local branch with this work done but will hold off on pushing as it'll mean a breaking change for some users

**Comment by bram-xsarus** [comment]
Hi @SingingBush as we can see, we really need your V3 version ;-)
Currently we cannot use the module anymore because of the Avalon dependency... What is your idea on releasing this ? Thanks!!!

**Comment by SingingBush** [comment]
I'd wanted to get the Saxon update completed before this. Perhaps though if you can try this branch with your project and confirm if it works as expected I can finish this off sooner. Please could you clone the repo, checkout the `remove_avalon` branch then do a maven install. You should then be able to use the *2.2.4-SNAPSHOT* version locally. 

This would really help me as I would like to maintain compatibility with the original as much as possible. Also, just out of curiosity, do you still require JDK 8 support? I'm likely to make JDK 11 the minimum in future.

**Comment by bram-xsarus** [comment]
Hi, no I don't need JDK8 support. We are developing an entire new service around Apache FOP, and use the instream objects feature to get barcode support. Input documents use the Krysalis namespace and we tried to achieve some backwards compatibility. Will try the work-around you suggested, keep you posted. Thanks

**Comment by bram-xsarus** [comment]
For your info: the 2.2.4-SNAPSHOT worked for me. Thanks for your support

**Comment by SingingBush** [comment]
thanks @bram-xsarus, I'm going to make this a change that's merged in for the 2.3.0 release which should be available from maven central in the next few days.

**Comment by SingingBush** [comment]
merged into main ready for 2.3.0 release

**Comment by Lonzak** [comment]
I was curious how you were able to remove the avalon framework. So I checked the code and basically you copied the used classes from the avalon framework to the barcode4j library:

    /**

        This class is essentially a copy of org.apache.avalon.framework.configuration.ConfigurationException
        */

Doesn't this beats the purpose and the avalon framework better remains like it is, to reflect that the framework is used?
In case some security issue are found in the framework, probably nobody remembers that there are still vulnerable copies in the barcode lib...

**Comment by SingingBush** [comment]
Avalon has been dead for years. It's not being maintained at all. Copying the configuration classes was the simplest way to start unpicking it. Now that those classes have been brought in the code will at least be maintained within this project, something that will simply not happen otherwise. Over time it's likely to evolve further.
