### ISSUE TITLE
barcode4j-fop-ext depends on barcode4g-xgc which is not published

### ISSUE THREAD

**Issue by rzaq-alshoshan** [SingingBush/barcode4j#16]
Hi @SingingBush again : )
First of all, thank you for the efforts in publishing the 2.2.0 release.
I tried using the barcode4j-fop-ext library, but for some reason it wasn't recognized, as not all dependencies were loaded and checked (we have private maven repo, which will not fetch any public library not uploaded in public maven central, for some reason).
I think the solution is to publish the barcode4g-xgc library.

Thank you again for the efforts.

**Comment by SingingBush** [comment]
doh! ok no problem, I'll re-release it today
