### ISSUE TITLE
Difficulty getting CLI to work

### ISSUE THREAD

**Issue by J-Cat** [SingingBush/barcode4j#18]
Not sure how to get CLI to work with this project.  I've tried running with the JAR file and with java -cp with no luck.

(I'm sure it is something I am not understanding as I don't spend much time with Java)

**Comment by SingingBush** [comment]
There are some required args when running the cli app. eg `-s EAN128 -f "image/svg+xml" 12345679`.

From a terminal this would be `java -jar barcode4j-cli-2.2.2-SNAPSHOT.jar -s EAN128 -f "image/svg+xml" 12345679`.

When I'm using the cli code it's normally from within the IDE in which case I'll make a run configuration in Intellij with the required args

**Comment by SingingBush** [comment]
The maven build now creates an uber jar (jar with all dependencies bundled with it) so it can be run standalone.

I've tested this by running `mvn clean package` in the project root then doing:

```
java -jar barcode4j-cli/target/barcode4j-cli-2.2.2-SNAPSHOT-jar-with-dependencies.jar -s EAN128 -f "image/svg+xml" 12345679
```

which outputs svg xml to std out. Use `--help` to see available options. Hope this resolves the issue for you
