### ISSUE TITLE
Releases Schedule

### ISSUE THREAD

**Issue by rzaq-alshoshan** [SingingBush/barcode4j#39]
Hi @SingingBush,

Thank you again for the great efforts in maintaining this library.

Do you have any releases scheduled soon ? or in other words, what is the frequency of releases you are planning to have ?

I am using the library, and multiple dependencies require updates (which truly don't want to do them one by one regularly, as I am only using them through this one). If you need any help in doing so I will be happy to assist in what I can.

**Comment by SingingBush** [comment]
I have a few feature branches on the go that I intended to do before Christmas however real life got in the way. I can do a release today for dependency updates. The next thing I really want to finish is proper Saxon support which I'd been getting on with using a trial license.
Just out of interest, what Java version are you using? I'd like to know if people still need JDK 8 support

**Comment by SingingBush** [comment]
I've tagged & created a release for _2.2.2_. The main branch was already updated, I just hadn't done a release as I was waiting until the feature work is done. It'll be a little while before it's available from maven central but certainly ready before the end of the weekend. 

Expect some _2.3.x_ releases over the next few months with saxon support being made available (see #8). I suspect it'll be v3 before I remove the dependency on Avalon (see #15)

**Comment by rzaq-alshoshan** [comment]
> I have a few feature branches on the go that I intended to do before Christmas however real life got in the way. I can do a release today for dependency updates. The next thing I really want to finish is proper Saxon support which I'd been getting on with using a trial license. Just out of interest, what Java version are you using? I'd like to know if people still need JDK 8 support

For Saxon support, I didn't write any xslt extensions before, but I can help in providing a Saxon EE version if needed.

For your question, I am using multiple JDK versions (8,11,17) for multiple projects. I think (maybe I am biased here) Java 8 support can be extended, at least for the current release train (2.x.x) as it is meant to be drop in replacement for the original library.

**Comment by SingingBush** [comment]
ok thanks, when I push my saxon changes perhaps you can give it a go. The new release is on maven central now:

```xml
<dependency>
    <groupId>com.singingbush</groupId>
    <artifactId>barcode4j</artifactId>
    <version>2.2.2</version>
</dependency>
```

**Comment by SingingBush** [comment]
@rzaq-alshoshan there is now a `2.2.3-SNAPSHOT` in maven central as I'm working toward a new release. If possible, would you be able to enable snapshots for you maven installation and try it out. I'd like to do a new release in the next few days so would be good to get feedback from users if there are any issues with the snapshot build.
