### ISSUE TITLE
encoding problem with migrated sources

### ISSUE THREAD

**Issue by SingingBush** [SingingBush/barcode4j#4]
although the files are all UTF-8 there are charset problems that need fixing. I suspect this was a problem in Sourceforge, perhaps when going from CVS to svn. An example is files that are showing `Jeremias M�rki` instead of `Jeremias Märki` even though the charset is UTF-8.

As there's a lot of `�` chars in the test classes some care will need to be taken to ensure they are set to the intended values.

**Comment by SingingBush** [comment]
Seems like all sources were *ISO-8859-1* originally

**Comment by mrhuber71** [comment]
Maybe this issue is now obsolet. Since commit 3b6581b7a44 Project character set is changed to UTF-8.

**Comment by SingingBush** [comment]
yeah this can be closed
